## Taller

## Moreno Puente Emilia Cristina

## Inversa

In [1]:
# ----------------------------- logging --------------------------
import logging
from sys import stdout
from datetime import datetime

logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s][%(levelname)s] %(message)s",
    stream=stdout,
    datefmt="%m-%d %H:%M:%S",
)
logging.info(datetime.now())

import numpy as np


# ####################################################################
def gauss_jordan(A: np.ndarray) -> np.ndarray:
    """Realiza la eliminación de Gauss-Jordan

    ## Parameters

    ``A``: matriz del sistema de ecuaciones lineales. Debe ser de tamaño n-by-(k), donde n es el número de incógnitas.

    ## Return

    ``A``: matriz reducida por filas.

    """
    if not isinstance(A, np.ndarray):
        logging.debug("Convirtiendo A a numpy array.")
        A = np.array(A, dtype=float)
    n = A.shape[0]

    for i in range(0, n):  # loop por columna

        # --- encontrar pivote
        p = None  # default, first element
        for pi in range(i, n):
            if A[pi, i] == 0:
                # must be nonzero
                continue

            if p is None:
                # first nonzero element
                p = pi
                continue

            if abs(A[pi, i]) < abs(A[p, i]):
                p = pi

        if p is None:
            # no pivot found.
            raise ValueError("No existe solución única.")

        if p != i:
            # swap rows
            logging.debug(f"Intercambiando filas {i} y {p}")
            _aux = A[i, :].copy()
            A[i, :] = A[p, :].copy()
            A[p, :] = _aux

        # --- Eliminación: loop por fila
        # for j in range(i + 1, n): # Eliminación gaussiana
        for j in range(n):  # Gauss-Jordan
            if j == i:
                continue  # skip pivot row

            m = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - m * A[i, i:]

            # dividir para la diagonal
        A[i, :] = A[i, :] / A[i, i]

        logging.info(f"\n{A}")

    if A[n - 1, n - 1] == 0:
        raise ValueError("No existe solución única.")

        print(f"\n{A}")
    # # --- Sustitución hacia atrás
    # solucion = np.zeros(n)
    # solucion[n - 1] = A[n - 1, n] / A[n - 1, n - 1]

    # for i in range(n - 2, -1, -1):
    #     suma = 0
    #     for j in range(i + 1, n):
    #         suma += A[i, j] * solucion[j]
    #     solucion[i] = (A[i, n] - suma) / A[i, i]

    return A

[01-13 21:44:16][INFO] 2026-01-13 21:44:16.589112


In [2]:
import numpy as np
A = [[1, 3, 4], [2, 1, 3], [4, 2, 1]]

n = len(A)
A_aug = np.hstack((A, np.eye(n)))

print(gauss_jordan(A_aug))


[01-13 21:44:20][INFO] 
[[  1.   3.   4.   1.   0.   0.]
 [  0.  -5.  -5.  -2.   1.   0.]
 [  0. -10. -15.  -4.   0.   1.]]
[01-13 21:44:20][INFO] 
[[ 1.   0.   1.  -0.2  0.6  0. ]
 [-0.   1.   1.   0.4 -0.2 -0. ]
 [ 0.   0.  -5.   0.  -2.   1. ]]
[01-13 21:44:20][INFO] 
[[ 1.   0.   0.  -0.2  0.2  0.2]
 [-0.   1.   0.   0.4 -0.6  0.2]
 [-0.  -0.   1.  -0.   0.4 -0.2]]
[[ 1.   0.   0.  -0.2  0.2  0.2]
 [-0.   1.   0.   0.4 -0.6  0.2]
 [-0.  -0.   1.  -0.   0.4 -0.2]]


In [3]:

A = [[1.,2,3],[0,1,4],[5,6,0]]
n = len(A)
A_aug = np.hstack((A, np.eye(n)))

print(gauss_jordan(A_aug))


[01-13 21:44:23][INFO] 
[[  1.   2.   3.   1.   0.   0.]
 [  0.   1.   4.   0.   1.   0.]
 [  0.  -4. -15.  -5.   0.   1.]]
[01-13 21:44:23][INFO] 
[[ 1.  0. -5.  1. -2.  0.]
 [ 0.  1.  4.  0.  1.  0.]
 [ 0.  0.  1. -5.  4.  1.]]
[01-13 21:44:23][INFO] 
[[  1.   0.   0. -24.  18.   5.]
 [  0.   1.   0.  20. -15.  -4.]
 [  0.   0.   1.  -5.   4.   1.]]
[[  1.   0.   0. -24.  18.   5.]
 [  0.   1.   0.  20. -15.  -4.]
 [  0.   0.   1.  -5.   4.   1.]]


In [4]:

A = [[4.,2,1],[2,1,3],[1,3,4]]
n = len(A)
A_aug = np.hstack((A, np.eye(n)))

print(gauss_jordan(A_aug))



[01-13 21:44:25][INFO] 
[[  1.   3.   4.   0.   0.   1.]
 [  0.  -5.  -5.   0.   1.  -2.]
 [  0. -10. -15.   1.   0.  -4.]]
[01-13 21:44:25][INFO] 
[[ 1.   0.   1.   0.   0.6 -0.2]
 [-0.   1.   1.  -0.  -0.2  0.4]
 [ 0.   0.  -5.   1.  -2.   0. ]]
[01-13 21:44:25][INFO] 
[[ 1.   0.   0.   0.2  0.2 -0.2]
 [-0.   1.   0.   0.2 -0.6  0.4]
 [-0.  -0.   1.  -0.2  0.4 -0. ]]
[[ 1.   0.   0.   0.2  0.2 -0.2]
 [-0.   1.   0.   0.2 -0.6  0.4]
 [-0.  -0.   1.  -0.2  0.4 -0. ]]


## Descomposicion LU

In [7]:
%load_ext autoreload
%autoreload 2

from src import descomposicion_LU
from src import resolver_LU

[01-13 21:45:17][INFO] 2026-01-13 21:45:17.253989
[01-13 21:45:17][INFO] 2026-01-13 21:45:17.256845


ImportError: cannot import name 'eliminacion_gaussiana' from 'src' (consider renaming 'c:\\IdkHowFoundMe\\Talleres\\TallerLuD\\src\\__init__.py' if it has the same name as a library you intended to import)

In [61]:
A = [[1.,3,4],[2,1,3],[4,2,1]]
b= [1,2,4]

L,U= descomposicion_LU(A)
print("L es")
print(L)
print("U es")
print(U)

x = resolver_LU(L, U, b)
print("Solución x =\n", x)



[01-13 17:47:50][INFO] 
[[  1.   3.   4.]
 [  0.  -5.  -5.]
 [  0. -10. -15.]]
[01-13 17:47:50][INFO] 
[[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]
[01-13 17:47:50][INFO] 
[[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]
L es
[[1. 0. 0.]
 [2. 1. 0.]
 [4. 2. 1.]]
U es
[[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]
[01-13 17:47:50][INFO] Sustitución hacia adelante
[01-13 17:47:50][INFO] y = 
[[1.]
 [0.]
 [0.]]
[01-13 17:47:50][INFO] Sustitución hacia atrás
[01-13 17:47:50][INFO] i = 1
[01-13 17:47:50][INFO] suma = [0.]
[01-13 17:47:50][INFO] U[i, i] = -5.0
[01-13 17:47:50][INFO] y[i] = [0.]
[01-13 17:47:50][INFO] i = 0
[01-13 17:47:50][INFO] suma = [0.]
[01-13 17:47:50][INFO] U[i, i] = 1.0
[01-13 17:47:50][INFO] y[i] = [1.]
Solución x =
 [[ 1.]
 [-0.]
 [-0.]]


In [71]:
A = [[1.,3,4],[2,1,3],[4,2,1]]
b= [3,-5,2]

L,U= descomposicion_LU(A)
print("L es")
print(L)
print("U es")
print(U)

x = resolver_LU(L, U, b)
print("Solución x =\n", x)

[01-13 17:57:33][INFO] 
[[  1.   3.   4.]
 [  0.  -5.  -5.]
 [  0. -10. -15.]]
[01-13 17:57:33][INFO] 
[[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]
[01-13 17:57:33][INFO] 
[[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]
L es
[[1. 0. 0.]
 [2. 1. 0.]
 [4. 2. 1.]]
U es
[[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]
[01-13 17:57:33][INFO] Sustitución hacia adelante
[01-13 17:57:33][INFO] y = 
[[  3.]
 [-11.]
 [ 12.]]
[01-13 17:57:33][INFO] Sustitución hacia atrás
[01-13 17:57:33][INFO] i = 1
[01-13 17:57:33][INFO] suma = [12.]
[01-13 17:57:33][INFO] U[i, i] = -5.0
[01-13 17:57:33][INFO] y[i] = [-11.]
[01-13 17:57:33][INFO] i = 0
[01-13 17:57:33][INFO] suma = [4.2]
[01-13 17:57:33][INFO] U[i, i] = 1.0
[01-13 17:57:33][INFO] y[i] = [3.]
Solución x =
 [[-1.2]
 [ 4.6]
 [-2.4]]


In [72]:
A = [[1.,3,4],[2,1,3],[4,2,1]]
b= [7,8,-1]

L,U= descomposicion_LU(A)
print("L es")
print(L)
print("U es")
print(U)

x = resolver_LU(L, U, b)
print("Solución x =\n", x)

[01-13 17:57:48][INFO] 
[[  1.   3.   4.]
 [  0.  -5.  -5.]
 [  0. -10. -15.]]
[01-13 17:57:48][INFO] 
[[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]
[01-13 17:57:48][INFO] 
[[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]
L es
[[1. 0. 0.]
 [2. 1. 0.]
 [4. 2. 1.]]
U es
[[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]
[01-13 17:57:48][INFO] Sustitución hacia adelante
[01-13 17:57:48][INFO] y = 
[[  7.]
 [ -6.]
 [-17.]]
[01-13 17:57:48][INFO] Sustitución hacia atrás
[01-13 17:57:48][INFO] i = 1
[01-13 17:57:48][INFO] suma = [-17.]
[01-13 17:57:48][INFO] U[i, i] = -5.0
[01-13 17:57:48][INFO] y[i] = [-6.]
[01-13 17:57:48][INFO] i = 0
[01-13 17:57:48][INFO] suma = [7.]
[01-13 17:57:48][INFO] U[i, i] = 1.0
[01-13 17:57:48][INFO] y[i] = [7.]
Solución x =
 [[ 8.8817842e-16]
 [-2.2000000e+00]
 [ 3.4000000e+00]]


In [73]:
A = [[1.,2,3],[0,1,4],[5,6,0]]
b= [1,2,4]

L,U= descomposicion_LU(A)
print("L es")
print(L)
print("U es")
print(U)

x = resolver_LU(L, U, b)
print("Solución x =\n", x)

[01-13 17:58:15][INFO] 
[[  1.   2.   3.]
 [  0.   1.   4.]
 [  0.  -4. -15.]]
[01-13 17:58:15][INFO] 
[[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]
[01-13 17:58:15][INFO] 
[[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]
L es
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 5. -4.  1.]]
U es
[[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]
[01-13 17:58:15][INFO] Sustitución hacia adelante
[01-13 17:58:15][INFO] y = 
[[1.]
 [2.]
 [7.]]
[01-13 17:58:15][INFO] Sustitución hacia atrás
[01-13 17:58:15][INFO] i = 1
[01-13 17:58:15][INFO] suma = [28.]
[01-13 17:58:15][INFO] U[i, i] = 1.0
[01-13 17:58:15][INFO] y[i] = [2.]
[01-13 17:58:15][INFO] i = 0
[01-13 17:58:15][INFO] suma = [-31.]
[01-13 17:58:15][INFO] U[i, i] = 1.0
[01-13 17:58:15][INFO] y[i] = [1.]
Solución x =
 [[ 32.]
 [-26.]
 [  7.]]


In [63]:
A = [[1.,2,3],[0,1,4],[5,6,0]]
b= [3,-5,1]

L,U= descomposicion_LU(A)
print("L es")
print(L)
print("U es")
print(U)

x = resolver_LU(L, U, b)
print("Solución x =\n", x)

[01-13 17:49:50][INFO] 
[[  1.   2.   3.]
 [  0.   1.   4.]
 [  0.  -4. -15.]]
[01-13 17:49:50][INFO] 
[[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]
[01-13 17:49:50][INFO] 
[[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]
L es
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 5. -4.  1.]]
U es
[[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]
[01-13 17:49:50][INFO] Sustitución hacia adelante
[01-13 17:49:50][INFO] y = 
[[  3.]
 [ -5.]
 [-34.]]
[01-13 17:49:50][INFO] Sustitución hacia atrás
[01-13 17:49:50][INFO] i = 1
[01-13 17:49:50][INFO] suma = [-136.]
[01-13 17:49:50][INFO] U[i, i] = 1.0
[01-13 17:49:50][INFO] y[i] = [-5.]
[01-13 17:49:50][INFO] i = 0
[01-13 17:49:50][INFO] suma = [160.]
[01-13 17:49:50][INFO] U[i, i] = 1.0
[01-13 17:49:50][INFO] y[i] = [3.]
Solución x =
 [[-157.]
 [ 131.]
 [ -34.]]


In [74]:
A = [[1.,2,3],[0,1,4],[5,6,0]]
b= [7,8,-1]

L,U= descomposicion_LU(A)
print("L es")
print(L)
print("U es")
print(U)

x = resolver_LU(L, U, b)
print("Solución x =\n", x)

[01-13 17:58:33][INFO] 
[[  1.   2.   3.]
 [  0.   1.   4.]
 [  0.  -4. -15.]]
[01-13 17:58:33][INFO] 
[[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]
[01-13 17:58:33][INFO] 
[[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]
L es
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 5. -4.  1.]]
U es
[[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]
[01-13 17:58:33][INFO] Sustitución hacia adelante
[01-13 17:58:33][INFO] y = 
[[ 7.]
 [ 8.]
 [-4.]]
[01-13 17:58:33][INFO] Sustitución hacia atrás
[01-13 17:58:33][INFO] i = 1
[01-13 17:58:33][INFO] suma = [-16.]
[01-13 17:58:33][INFO] U[i, i] = 1.0
[01-13 17:58:33][INFO] y[i] = [8.]
[01-13 17:58:33][INFO] i = 0
[01-13 17:58:33][INFO] suma = [36.]
[01-13 17:58:33][INFO] U[i, i] = 1.0
[01-13 17:58:33][INFO] y[i] = [7.]
Solución x =
 [[-29.]
 [ 24.]
 [ -4.]]


In [64]:
A = [[1.,3,4],[2,1,3],[4,2,1]]
b= [1,2,4]

L,U= descomposicion_LU(A)
print("L es")
print(L)
print("U es")
print(U)

x = resolver_LU(L, U, b)
print("Solución x =\n", x)

[01-13 17:50:06][INFO] 
[[  1.   3.   4.]
 [  0.  -5.  -5.]
 [  0. -10. -15.]]
[01-13 17:50:06][INFO] 
[[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]
[01-13 17:50:06][INFO] 
[[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]
L es
[[1. 0. 0.]
 [2. 1. 0.]
 [4. 2. 1.]]
U es
[[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]
[01-13 17:50:06][INFO] Sustitución hacia adelante
[01-13 17:50:06][INFO] y = 
[[1.]
 [0.]
 [0.]]
[01-13 17:50:06][INFO] Sustitución hacia atrás
[01-13 17:50:06][INFO] i = 1
[01-13 17:50:06][INFO] suma = [0.]
[01-13 17:50:06][INFO] U[i, i] = -5.0
[01-13 17:50:06][INFO] y[i] = [0.]
[01-13 17:50:06][INFO] i = 0
[01-13 17:50:06][INFO] suma = [0.]
[01-13 17:50:06][INFO] U[i, i] = 1.0
[01-13 17:50:06][INFO] y[i] = [1.]
Solución x =
 [[ 1.]
 [-0.]
 [-0.]]


In [76]:
A = [[4.,2,1],[2,1,3],[1,3,4]]

b= [1,2,4]

L,U= descomposicion_LU(A)
print("L es")
print(L)
print("U es")
print(U)

x = resolver_LU(L, U, b)
print("Solución x =\n", x)

[01-13 17:59:14][INFO] 
[[4.   2.   1.  ]
 [0.   0.   2.5 ]
 [0.   2.5  3.75]]


ValueError: No existe solución única.

In [77]:
A = [[4.,2,1],[2,1,3],[1,3,4]]

b= [3,-5,2]

L,U= descomposicion_LU(A)
print("L es")
print(L)
print("U es")
print(U)

x = resolver_LU(L, U, b)
print("Solución x =\n", x)

[01-13 17:59:26][INFO] 
[[4.   2.   1.  ]
 [0.   0.   2.5 ]
 [0.   2.5  3.75]]


ValueError: No existe solución única.

In [75]:
A = [[4.,2,1],[2,1,3],[1,3,4]]

b= [7,8,-1]

L,U= descomposicion_LU(A)
print("L es")
print(L)
print("U es")
print(U)

x = resolver_LU(L, U, b)
print("Solución x =\n", x)

[01-13 17:59:02][INFO] 
[[4.   2.   1.  ]
 [0.   0.   2.5 ]
 [0.   2.5  3.75]]


ValueError: No existe solución única.

In [68]:
A = [[2,4,6,1],[4,7,5,-6],[2,5,18,10],[6,12,38,16]]
b= [1,2,4,5]

L,U= descomposicion_LU(A)
print("L es")
print(L)
print("U es")
print(U)

x = resolver_LU(L, U, b)
print("Solución x =\n", x)

[01-13 17:56:00][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  1. 12.  9.]
 [ 0.  0. 20. 13.]]
[01-13 17:56:00][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0. 20. 13.]]
[01-13 17:56:00][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[01-13 17:56:00][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
L es
[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 1. -1.  1.  0.]
 [ 3. -0.  4.  1.]]
U es
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[01-13 17:56:00][INFO] Sustitución hacia adelante
[01-13 17:56:00][INFO] y = 
[[  1.]
 [  0.]
 [  3.]
 [-10.]]
[01-13 17:56:00][INFO] Sustitución hacia atrás
[01-13 17:56:00][INFO] i = 2
[01-13 17:56:00][INFO] suma = [-1.11111111]
[01-13 17:56:00][INFO] U[i, i] = 5.0
[01-13 17:56:00][INFO] y[i] = [3.]
[01-13 17:56:00][INFO] i = 1
[01-13 17:56:00][INFO] suma = [3.13333333]
[01-13 17:56:00][INFO] U[i, i] = -1.0
[01-13 17:56:00][IN

In [69]:
A = [[2,4,6,1],[4,7,5,-6],[2,5,18,10],[6,12,38,16]]
b= [3,-5,2,6]

L,U= descomposicion_LU(A)
print("L es")
print(L)
print("U es")
print(U)

x = resolver_LU(L, U, b)
print("Solución x =\n", x)

[01-13 17:56:24][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  1. 12.  9.]
 [ 0.  0. 20. 13.]]
[01-13 17:56:24][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0. 20. 13.]]
[01-13 17:56:24][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[01-13 17:56:24][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
L es
[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 1. -1.  1.  0.]
 [ 3. -0.  4.  1.]]
U es
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[01-13 17:56:24][INFO] Sustitución hacia adelante
[01-13 17:56:24][INFO] y = 
[[  3.]
 [-11.]
 [-12.]
 [ 45.]]
[01-13 17:56:24][INFO] Sustitución hacia atrás
[01-13 17:56:24][INFO] i = 2
[01-13 17:56:24][INFO] suma = [5.]
[01-13 17:56:24][INFO] U[i, i] = 5.0
[01-13 17:56:24][INFO] y[i] = [-12.]
[01-13 17:56:24][INFO] i = 1
[01-13 17:56:24][INFO] suma = [-16.2]
[01-13 17:56:24][INFO] U[i, i] = -1.0
[01-13 17:56:24][INFO] y[i] = [

In [70]:
A = [[2,4,6,1],[4,7,5,-6],[2,5,18,10],[6,12,38,16]]
b= [7,8,-1,0]

L,U= descomposicion_LU(A)
print("L es")
print(L)
print("U es")
print(U)

x = resolver_LU(L, U, b)
print("Solución x =\n", x)

[01-13 17:57:07][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  1. 12.  9.]
 [ 0.  0. 20. 13.]]
[01-13 17:57:07][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0. 20. 13.]]
[01-13 17:57:07][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[01-13 17:57:07][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
L es
[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 1. -1.  1.  0.]
 [ 3. -0.  4.  1.]]
U es
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[01-13 17:57:07][INFO] Sustitución hacia adelante
[01-13 17:57:07][INFO] y = 
[[  7.]
 [ -6.]
 [-14.]
 [ 35.]]
[01-13 17:57:07][INFO] Sustitución hacia atrás
[01-13 17:57:07][INFO] i = 2
[01-13 17:57:07][INFO] suma = [3.88888889]
[01-13 17:57:07][INFO] U[i, i] = 5.0
[01-13 17:57:07][INFO] y[i] = [-14.]
[01-13 17:57:07][INFO] i = 1
[01-13 17:57:07][INFO] suma = [-6.06666667]
[01-13 17:57:07][INFO] U[i, i] = -1.0
[01-13 17:57:07][